server:
  port: 8889


logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:myaql://127.0.0.1:3306/course
    username: root
    password: 123456